"""added foreign key user_id to the films

Revision ID: 109cc7a118e4
Revises: 4e7c10d6500d
Create Date: 2024-01-17 14:20:12.885544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109cc7a118e4'
down_revision = '4e7c10d6500d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
