"""added category in the todo list

Revision ID: 455e5721ce8d
Revises: 
Create Date: 2023-11-19 13:27:35.318890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455e5721ce8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
