"""added comment_date to the Feedback model

Revision ID: 4e7c10d6500d
Revises: f14181dfe0bd
Create Date: 2023-12-04 09:41:49.265395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7c10d6500d'
down_revision = 'f14181dfe0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('comment_date')

    # ### end Alembic commands ###
